name: Build APK and Test

on:
  push:
    branches: [ main, master ]  # شاخه‌های مورد نظر
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ۱. کلون کردن پروژه با نسخه جدیدتر Checkout
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main  # یا master، بسته به شاخه دیفالت مخزن

    # ۲. نصب JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    # ۳. نصب Go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    # ۴. نصب NDK
    - name: Set up Android NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        echo "export ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "ndk;28.0.13004108" | tee -a $GITHUB_WORKSPACE/NDK_VERSION
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.0.13004108"

    # ۵. نصب gomobile
    - name: Install gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    # ۶. تولید Gradle Wrapper اگه وجود نداشته باشه
    - name: Initialize Gradle Wrapper
      run: |
        if [ ! -f "gradlew" ]; then
          echo "gradlew not found, initializing Gradle Wrapper..."
          curl -sL https://services.gradle.org/distributions/gradle-8.4-bin.zip -o gradle-8.4-bin.zip
          unzip -q gradle-8.4-bin.zip
          mv gradle-8.4/bin/gradlew .
          chmod +x gradlew
          rm -rf gradle-8.4-bin.zip gradle-8.4
        else
          chmod +x gradlew
        fi

    # ۷. بیلد libcore
    - name: Build libcore
      run: make libcore

    # ۸. دانلود فایل‌های Geo
    - name: Download Geo files
      run: make assets

    # ۹. اجرای تست‌ها
    - name: Run Tests
      run: |
        ./gradlew test --stacktrace

    # ۱۰. بیلد APK
    - name: Build APK
      run: |
        ./gradlew assembleDebug --stacktrace

    # ۱۱. آپلود APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
