name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ۱. کلون کردن پروژه
    - name: Checkout code
      uses: actions/checkout@v4

    # ۲. نصب JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    # ۳. نصب Go (برای بیلد libcore)
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    # ۴. نصب NDK
    - name: Set up Android NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        echo "export ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "ndk;28.0.13004108" | tee -a $GITHUB_WORKSPACE/NDK_VERSION
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.0.13004108"

    # ۵. نصب gomobile
    - name: Install gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    # ۶. تولید فایل Keystore از Base64
    - name: Decode Base64 to Keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: android_keystore.jks
        encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

    # ۷. بیلد libcore
    - name: Build libcore
      run: make libcore

    # ۸. دانلود فایل‌های Geo
    - name: Download Geo files
      run: make assets

    # ۹. بیلد APK (نسخه Release برای امضا)
    - name: Build Signed APK
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
      env:
        # متغیرهای محیطی برای امضا
        KEYSTORE_PATH: android_keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    # ۱۰. آپلود APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
