name: Build APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
  # ۱. Checkout با شاخه درست
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      ref: master  # تغییر از 'main' به 'master'
      path: .      # مطمئن می‌شه تو ریشه کار می‌کنه

  # ۲. دیباگ: چک کردن دایرکتوری
  - name: Check directory
    run: |
      pwd
      ls -la

  # ۳. دسترسی به gradlew
  - name: Make gradlew executable
    run: |
      chmod +x gradlew
      ls -l gradlew

  # ۴. نصب JDK 21
  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'zulu'

  # ۵. بیلد APK
  - name: Build APK
    run: |
      ./gradlew assembleDebug --stacktrace

  # ۶. آپلود APK
  - name: Upload APK
    uses: actions/upload-artifact@v4
    with:
      name: app-debug-apk
      path: app/build/outputs/apk/debug/app-debug.apk
