name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # یا 'zulu' یا 'temurin' بسته به توزیع جاوا که استفاده می‌کنید
        java-version: '11'

    - name: Run configure script
      run: ./path/to/configure # مسیر صحیح به فایل configure را مشخص کنید

    - name: Build with Gradle
      run: ./gradlew build
