name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ۱. کلون کردن پروژه
    - name: Checkout code
      uses: actions/checkout@v4

    # ۲. نصب JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    # ۳. نصب Go
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    # ۴. نصب NDK
    - name: Set up Android NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        export ANDROID_HOME=/usr/lib/android-sdk
        echo "export ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "ndk;28.0.13004108" | tee -a $GITHUB_WORKSPACE/NDK_VERSION
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.0.13004108"

    # ۵. نصب gomobile
    - name: Install gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    # ۶. بیلد libcore
    - name: Build libcore
      run: make libcore

    # ۷. دانلود فایل‌های Geo
    - name: Download Geo files
      run: make assets

    # ۸. چک کردن وجود gradlew
    - name: Check Gradle Wrapper
      run: |
        if [ ! -f "gradlew" ]; then
          echo "gradlew not found, initializing Gradle Wrapper..."
          gradle wrapper --gradle-version=8.4
        fi
        chmod +x gradlew

    # ۹. بیلد APK
    - name: Build APK
      run: |
        ./gradlew assembleDebug --stacktrace

    # ۱۰. آپلود APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
